#### Capacity building and development

::: {custom-style='Citation'}
This includes technology transfer, education and learning, south-south exchange, knowledge sharing (including traditional knowledge), scientific cooperation and information networks, developing communities of practice and task forces, access and benefit sharing (ABS) under the Nagoya Protocol, R&D and investment in green technologies, institutional strengthening and establishment of emergency response capabilities, and the development of transparent monitoring and reporting systems, and mainstreaming concepts and values related to biodiversity and climate so that people are aware of their importance, and capacitated to deal with their deterioriation.
:::

<br>

::: {custom-style='Text'}
The AI model identified no targets that could relate to this nature-based solution theme:
:::

<br>




**National Biodiversity Targets**:

-   There are no targets identified that relate to this theme.



​

**Other targets**:

-   There are no targets identified that relate to this theme.



​

**NDC targets**:

-   There are no targets identified that relate to this theme.



​




<br>

::: {custom-style='Text'}
Of these, no pair shows opportunities for further alignment with each other ..
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl8', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl20
library(flextable)
library(dplyr)
if (nrow(df18)  == 0) {
    invisible(NULL)
} else {df18 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
**AI-generated summary – Capacity building and development**


:::

<br>

