#### Grassland management and protection

::: {custom-style='Citation'}
This includes river, inland water and wetland protection, peatland rewetting, avoiding peat impacts, freshwater ecosystem protection, wetland management, service management of freshwater ecosystems, peatland restoration, dune restoration, freshwater ecosystem restoration, catchment restoration, watershed protection, restoration and reduced conversion of coastal wetlands, restoration and reduced conversion of peatlands, ,and sustainable fishery.
:::

<br>

::: {custom-style='Text'}
The AI model identified no targets that could relate to this nature-based solution theme:
:::

<br>




**National Biodiversity Targets**:

-   There are no targets identified that relate to this theme.



​

**Other targets**:

-   There are no targets identified that relate to this theme.



​

**NDC targets**:

-   There are no targets identified that relate to this theme.



​




<br>

::: {custom-style='Text'}
Of these, no pair shows opportunities for further alignment with each other ..
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl2', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl8
library(flextable)
library(dplyr)
if (nrow(df6)  == 0) {
    invisible(NULL)
} else {df6 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
**AI-generated summary – Grassland management and protection**


:::

<br>

