#### Protection and restoration of wetlands and freshwater ecosystems

::: {custom-style='Citation'}
This includes avoiding grassland conversion, grassland protection, savanna protection, avoiding shrubland conversion, sustainable grazing, optimal grazing intensity, conservation agriculture, grassland restoration, savanna restoration, degraded land restoration, tree intercropping, land conservation, and avoiding desertification.
:::

<br>

::: {custom-style='Text'}
The AI model identified no targets that could relate to this nature-based solution theme:
:::

<br>




**National Biodiversity Targets**:

-   There are no targets identified that relate to this theme.



​

**Other targets**:

-   There are no targets identified that relate to this theme.



​

**NDC targets**:

-   There are no targets identified that relate to this theme.



​




<br>

::: {custom-style='Text'}
Of these, no pair shows opportunities for further alignment with each other ..
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl2', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl7
library(flextable)
library(dplyr)
if (nrow(df5)  == 0) {
    invisible(NULL)
} else {df5 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
**AI-generated summary – Protection and restoration of wetlands and freshwater ecosystems**


:::

<br>

