#### Agriculture, Forestry, and Other Land Use (AFOLU)

::: {custom-style='Citation'}
This includes reforestation, afforestation and forest restoration, sustainable forest management, enhancement of forest carbon stocks, reduce deforestation, REDD+, land management, agroforestry, and improved soil carbon sequestration.
:::

<br>

::: {custom-style='Text'}
The AI model identified 17 targets that could relate to this nature-based solution category:
:::

<br>


**LDN targets**:

-   **LDN Target 1**: Halt the conversion of forests and wetlands to other land cover classes

-   **LDN Target 2**: Restore and improve degraded forest (80% in the dry zone and 20% in the wet zone)

-   **LDN Target 3**: Increase forest cover from 29% to 32%

-   **LDN Target 4**: Reduce rate of soil degradation to improve land productivity and Soil Organic Carbon (SOC) stocks



​

**LDN targets**:

-   **NBT 2**: Ensure that by 2030 at least 30% of degraded terrestrial, inland waters, coastal, and marine ecosystems are identified and under appropriate restoration initiatives including enhanced connectivity and buffering, using relevant methods, recovery plans, monitoring, adequate resources, and inter-agency cooperation, to enhance biodiversity and ecosystem functions and services, ecological integrity, and connectivity

-   **NBT 8**: Minimize the impact of climate change on all levels of biodiversity, and increase their resilience through mitigation, adaptation, disaster risk reduction, and habitat conservation; supported by nature-based solutions, and ecosystem-based approaches, while minimizing negative and fostering positive impacts of climate action on biodiversity

-   **NBT 10**: Ensure that areas under agriculture, aquaculture, fisheries, mining, tourism, renewable energy generation, and forestry are managed sustainably and cause minimum impact on ecosystems and wild species; promoting food security, all forms of nature-based tourism; conserving and restoring biodiversity, and maintaining ecosystem functions and services to benefit people

-   **NBT 11**: Restore, maintain and enhance nature’s contributions to people, such as ecosystem functions and services, by the use of nature-based solutions and ecosystem-based approaches, for the benefit of all people and nature

-   **NBT 14**: Ensure the integration of varied biodiversity considerations and its multiple values into national policies, legal framework, strategies, plans, pollution control, strategic and environmental impact assessments, and all development processes, to allow informed biodiversity inclusive decision making, and national accounting if appropriate; influencing fiscal and financial flows to support the 2030 National Biodiversity Targets, with the required awareness and transformative communication



​

**LDN targets**:

-   **Agriculture NDC 1 (adaptation)**: Mainstreaming climate change considerations into agriculture

-   **Agriculture NDC 3 (adaptation)**: Revising Agroecological Map of Sri Lanka considering current and future scenarios

-   **Agriculture NDC 5 (adaptation)**: Sustainable land use and efficienct resource management for improved production & productivity

-   **Biodiversity NDC 1**: Identification and management of climate-sensitive areas, and restoration of degraded areas inside and outside protected area (PA) network to conserve habitats that are highly vulnerable to climate change

-   **Forestry NDC 1**: Sustainable management of forest and restoration of other degraded lands, at least 32% by 2035

-   **Forestry NDC 2**: Expansion, restoration, and sustainable management of trees outside forest (TROF)

-   **Forestry NDC 3**: Promote catchment protection in major rivers and cascade systems through tree planting

-   **L&D NDC 1**: National Level stocktaking and progress reviewing related to all L&D sectors such as but not exclusive to - Agriculture, Livestock and Fisheries, Infrastructure/ Transport, Education, Water, Health, Tele Communication, Tourism, Industries, Gender and Child Protection, Social Protection, Biodiversity and Forestry, Housing, Power and Energy, coastal and marine



​






<br>

::: {custom-style='Text'}
The AI model also compared all targets that pertain to Land degradation (LDN), all targets that pertain to Nature (NBSAP), and all targets that pertain to Climate Change (NDC). Of these, 76 pairs show opportunities for further alignment with each other (, as shown in **Table 3.\@ref(tab:tbl15)**. The country might want to explore these targets in more detail and consider areas for further alignment or aligned implementation.).
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl15', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl17
library(flextable)
library(dplyr)
if (nrow(df15)  == 0) {
    invisible(NULL)
} else {df15 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
The targets across the Land Degradation Neutrality Targets for Sri Lanka, the Nationally Determined Contributions (NDC), and the National Biodiversity Targets (NBT) exhibit significant alignment in addressing the Agriculture, Forestry, and Other Land Use (AFOLU) theme. For instance, the NDC's focus on sustainable land use and resource management aligns with the Land Degradation Neutrality Targets' aim to halt forest conversion and improve soil carbon stocks. Additionally, both the NDC and NBT emphasize the importance of restoring degraded ecosystems, highlighting a shared commitment to enhancing biodiversity and ecosystem services. However, while the NDC targets are more focused on climate-sensitive areas and sustainable management practices, the NBT targets appear to emphasize broader biodiversity considerations and ecosystem functions. Overall, these synergies present opportunities for integrated policy implementation.
:::

<br>

