#### Agriculture and livestock management

::: {custom-style='Citation'}
This includes climate-resilient crops, climate-resilient livestock management, climate-smart agriculture, insurance,  regenerative agriculture, crop diversification, integrated water management, grazing land management, agricultural land and soil management, post-harvest processing, sustainable intensification, agriculture and livestock disease management, agricultural education and consulting, increased food productivity, agroforestry, agricultural diversification, improved grazing land management, and reduced grassland conservation to cropland.
:::

<br>

::: {custom-style='Text'}
The AI model identified 12 targets that could relate to this nature-based solution category:
:::

<br>


**LDN targets**:

-   **LDN Target 4**: Reduce rate of soil degradation to improve land productivity and Soil Organic Carbon (SOC) stocks



​

**NBSAP targets**:

-   **NBT 10**: Ensure that areas under agriculture, aquaculture, fisheries, mining, tourism, renewable energy generation, and forestry are managed sustainably and cause minimum impact on ecosystems and wild species; promoting food security, all forms of nature-based tourism; conserving and restoring biodiversity, and maintaining ecosystem functions and services to benefit people



​

**NDC targets**:

-   **Agriculture NDC 1 (adaptation)**: Mainstreaming climate change considerations into agriculture

-   **Agriculture NDC 3 (adaptation)**: Revising Agroecological Map of Sri Lanka considering current and future scenarios

-   **Agriculture NDC 5 (adaptation)**: Sustainable land use and efficienct resource management for improved production & productivity

-   **Agriculture NDC 6 (adaptation)**: Reduce post-harvest losses and promote value addition of crops in a changing climate

-   **Agriculture NDC 2 (mitigation)**: Increase crop productivity and production through efficient resource management

-   **Fisheries NDC 3**: Develop climatic-resilient varieties, and farming and breeding technologies to increase climate resilience

-   **L&D NDC 1**: National Level stocktaking and progress reviewing related to all L&D sectors such as but not exclusive to - Agriculture, Livestock and Fisheries, Infrastructure/ Transport, Education, Water, Health, Tele Communication, Tourism, Industries, Gender and Child Protection, Social Protection, Biodiversity and Forestry, Housing, Power and Energy, coastal and marine

-   **Livestock NDC 1 (mitigation)**: Improve dairy sector productivity by introducing Good Animal Husbandry practices (GAHP) in consideration of managing herd, herd health, feed and by improving animal comfort and welfare

-   **Livestock NDC 1 (adaptation)**: Introduce adaptation measures, particularly genetic improvement, disease surveillance and forage improvement strategies to address climate impacts on ruminant livestock

-   **Livestock NDC 2 (adaptation)**: Introduce technological innovations and interventions, especially by improved feeding, disease surveillance and management strategies, to build resilience in poultry and swine farming



​






<br>

::: {custom-style='Text'}
The AI model also compared all targets that pertain to Land degradation (LDN), all targets that pertain to Nature (NBSAP), and all targets that pertain to Climate Change (NDC). Of these, 19 pairs show opportunities for further alignment with each other (as shown in **Table 3.\@ref(tab:tbl2)**. The country might want to explore these targets in more detail and consider areas for further alignment or aligned implementation).
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl2', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl4
library(flextable)
library(dplyr)
if (nrow(df2)  == 0) {
    invisible(NULL)
} else {df2 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
The targets across the Land Degradation Neutrality Targets for Sri Lanka, the Nationally Determined Contributions (NDC), and the Nature-Based Tourism (NBT) policy exhibit significant alignment in promoting sustainable agricultural practices. Notably, the NDC's emphasis on mainstreaming climate change considerations and developing climate-resilient varieties aligns well with the Land Degradation Neutrality Targets' focus on improving soil productivity and organic carbon stocks. Additionally, the NBT's commitment to sustainable management of agricultural areas complements the NDC's goals of enhancing crop productivity and reducing post-harvest losses. This synergy suggests a cohesive approach to addressing climate resilience and sustainable land use within the agricultural sector. Overall, these policies collectively support the overarching theme of sustainable agriculture and livestock management.
:::

<br>

