#### Capacity building and development

::: {custom-style='Citation'}
This includes technology transfer, education and learning, south-south exchange, knowledge sharing (including traditional knowledge), scientific cooperation and information networks, developing communities of practice and task forces, access and benefit sharing (ABS) under the Nagoya Protocol, R&D and investment in green technologies, institutional strengthening and establishment of emergency response capabilities, and the development of transparent monitoring and reporting systems, and mainstreaming concepts and values related to biodiversity and climate so that people are aware of their importance and capacitated to deal with their deterioration.
:::

<br>

::: {custom-style='Text'}
The AI model identified no targets that could relate to this nature-based solution category:
:::

<br>




**LDN targets**:

-   There are no targets identified that relate to this theme.



​

**NBSAP targets**:

-   There are no targets identified that relate to this theme.



​

**NDC targets**:

-   There are no targets identified that relate to this theme.



​




<br>

::: {custom-style='Text'}
The AI model also compared all targets that pertain to Land degradation (LDN), all targets that pertain to Nature (NBSAP), and all targets that pertain to Climate Change (NDC). Of these, no pair shows opportunities for further alignment with each other ..
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl17', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl20
library(flextable)
library(dplyr)
if (nrow(df18)  == 0) {
    invisible(NULL)
} else {df18 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
The targets from the National Biodiversity Targets (NBT) and the Nationally Determined Contributions (NDC) exhibit several opportunities for alignment in the context of capacity building and development. For instance, both policies emphasize the importance of capacity building to enhance resilience against climate change impacts on biodiversity, as seen in the alignment of NDC's focus on alternate livelihoods with NBT's conservation goals. Additionally, the NDC's initiatives for improving research and education align with NBT's targets on strengthening technology transfer and knowledge sharing. However, while the NDC targets address broader sectors, the NBT targets specifically focus on biodiversity, suggesting a potential for more integrated approaches that could enhance overall effectiveness in achieving both biodiversity and climate resilience objectives.
:::

<br>

