#### Species conservation and ecosystems

::: {custom-style='Citation'}
This includes halting human-induced extinction of species, controlling invasive alien species, sharing of genetic resources and their digital sequence information to ensure genetic diversity, and reducing human-wildlife conflict, for instance, creating reserves. This also includes ecosystem services and ecosystem-based adaptation across deserts, forests, grasslands, shrublands, tropical rainforests, oceans, coral reefs, lakes, marine coastal ecosystems, rivers, savanna, woodlands, sub-tropical, wetlands, and other biomes.
:::

<br>

::: {custom-style='Text'}
The AI model identified 29 targets that could relate to this nature-based solution category:
:::

<br>


**NBSAP targets**:

-   **NBT 1**: Ensure all inland, coastal, and marine areas are under participatory, integrated biodiversity-inclusive spatial planning at all levels; using appropriate tools and regulatory processes; to minimize biodiversity loss in areas of particular importance by 2030, while supporting sustainable use and respecting customary and traditional practices.

-   **NBT 2**: Ensure that by 2030 at least 30% of degraded terrestrial, inland waters, coastal, and marine ecosystems are identified and under appropriate restoration initiatives including enhanced connectivity and buffering, using relevant methods, recovery plans, monitoring, adequate resources, and inter-agency cooperation, to enhance biodiversity and ecosystem functions and services, ecological integrity, and connectivity

-   **NBT 3**: By 2030, ensure and enable 30% of key terrestrial, wetland, and coastal and marine areas of particular biodiversity importance are conserved through ecologically representative, connected, and equitably governed Protected Areas and OECMs that are integrated into wider landscapes and seascapes, using management plans and inter_x0002_agency cooperation; respecting traditional knowledge and customary practices of indigenous and local communities, within existing legal frameworks

-   **NBT 4**: By 2030, ensure urgent actions to halt extinction of threatened species, recover and conserve species in all key ecosystems, and preserve genetic diversity; including indigenous and migratory wild species, species listed in CITES, and indigenous crop and livestock species; targeting reduction of threat status for 30% of nationally threatened species, and increasing adaptive potential of species by using appropriate conservation methods, and minimizing human-wildlife conflict

-   **NBT 5**: Ensure that by 2030 the use, harvesting, and trade of wild species, is sustainable, safe and legal, preventing over-exploitation and illegal practices, minimizing impacts on non-target species, ecosystems, and risk of pathogen spill over; supported by legal procedures, monitoring, and guidelines, while respecting customary, wise, and sustainable use by indigenous peoples and local communities.

-   **NBT 6**: Eliminate, minimize, reduce, and mitigate the impacts of known or potentially invasive alien species (IAS) on biodiversity and ecosystem services, by identifying and managing pathways to prevent introductions by 50% and minimizing the establishment and/or spread of IAS, by using scientifically accepted or traditionally tested participatory approaches, backed by capacity building

-   **NBT 7**: Reduce pollution risks from identified sources to levels that are not harmful to biodiversity and ecosystem functions and services by 2030, backed by laws, regulations, waste management and other measures, to reduce pollution from waste and hazardous chemicals (by half), oil, plastics, agro-chemicals, and excess nutrients, using appropriate methods based on science and traditional knowledge

-   **NBT 8**: Minimize the impact of climate change on all levels of biodiversity, and increase their resilience through mitigation, adaptation, disaster risk reduction, and habitat conservation; supported by nature-based solutions, and ecosystem-based approaches, while minimizing negative and fostering positive impacts of climate action on biodiversity

-   **NBT 9**: Ensure that the management and use of wild species are sustainable and legal, thereby providing increased social, economic and environmental benefits for people, especially those heavily dependent on biodiversity, through sustainable biodiversity-based activities, products and services that enhance biodiversity and livelihoods, backed by laws and regulations while protecting sustainable customary, and traditional use by local communities

-   **NBT 10**: Ensure that areas under agriculture, aquaculture, fisheries, mining, tourism, renewable energy generation, and forestry are managed sustainably and cause minimum impact on ecosystems and wild species; promoting food security, all forms of nature-based tourism; conserving and restoring biodiversity, and maintaining ecosystem functions and services to benefit people

-   **NBT 11**: Restore, maintain and enhance nature’s contributions to people, such as ecosystem functions and services, by the use of nature-based solutions and ecosystem-based approaches, for the benefit of all people and nature

-   **NBT 12**: By 2030, significantly and sustainably increase and conserve the area, landscape quality, connectivity with nature, access to and benefits from green and blue spaces in urban and other densely populated areas, by mainstreaming the conservation and sustainable use of biodiversity and adopting biodiversity-inclusive sustainable urban planning; enabling biodiversity conservation, inclusive and sustainable urbanization, and enhancing human health and the quality of life

-   **NBT 13**: Take effective legal, policy, administrative and capacity-building action, to mainstream and ensure the fair and equitable sharing of monetary and non- monetary benefits that arise from the utilization of biological material—including genetic resources and derivative—for commercial use of its genetic material, biochemical features and/or related information value, including DSI and traditional knowledge associated with genetic resources, within the framework of national laws and policies, with the necessary safety procedures in place

-   **NBT 14**: Ensure the integration of varied biodiversity considerations and its multiple values into national policies, legal framework, strategies, plans, pollution control, strategic and environmental impact assessments, and all development processes, to allow informed biodiversity inclusive decision making, and national accounting if appropriate; influencing fiscal and financial flows to support the 2030 National Biodiversity Targets, with the required awareness and transformative communication

-   **NBT 15**: Take legal, administrative, and policy measures including incentives as appropriate for the varied levels of business to disclose and mitigate risks and negative impacts on biodiversity; while enabling benefiting, and benefiting from biodiversity; using nationally accepted procedures, standards, tools, mechanisms and incentives; to promote sustainable patterns of production to benefit the national economy

-   **NBT 19**: Increase effective and timely financial resources to Sri Lanka from all sources to close the biodiversity finance gap to implement the National Biodiversity Strategy and Action Plan and achieve the NBTs by 2030; attracting international financial flows and significantly increasing domestic resource mobilization; leveraging private finance--including matching donors with national biodiversity plans; encouraging locally adapted business modalities; and optimizing co-benefits and synergies through joint funding for biodiversity and climate action

-   **NBT 20**: Strengthen capacity-building and technology transfer for biodiversity research, conservation, monitoring and cooperation, including digital and other advanced technologies as well as traditional knowledge and practices; and fostering international, technical, and scientific cooperation and partnerships for effective management, conservation, and sustainable use of biodiversity

-   **NBT 21**: Ensure that the best available data, information and knowledge—including traditional knowledge—are available to guide evidence-based decision-making, effective and equitable governance, and integrated participatory management of biodiversity; with strengthened communication, awareness, education, monitoring, research and data management; while respecting the rights over knowledge of indigenous peoples and local communities

-   **NBT 24**: Build capacity to conserve biodiversity at all its levels and for the sustainable use of bioresources, with the active participation of motivated stakeholders to facilitate biodiversity conservation and achieve the National Biodiversity Targets and the 2050 biodiversity vision

-   **NBT 25**: Establish an effective operationalizing and reviewing framework and mechanism, through appropriate sectoral and inter-sectoral coordination and a whole-of-government, whole-of-society, and all actors approach for efficient implementation of the NBSAP and tracking and achieving the NBTs by 2030



​

**NBSAP targets**:

-   **Biodiversity NDC 1**: Identification and management of climate-sensitive areas, and restoration of degraded areas inside and outside protected area (PA) network to conserve habitats that are highly vulnerable to climate change

-   **Biodiversity NDC 3**: Expansion of protected area (PA) extent to enhance the ability of the PA network to function as an additional area to build resilience to climate change

-   **Biodiversity NDC 4**: Strengthen ex-situ conservation programmes covering climate-vulnerable taxa

-   **Biodiversity NDC 5**: Effective management of the spread of Invasive Alien Species (IAS) triggered by favorable climate conditions

-   **Coastal and Marine NDC 4**: Identify, designate, and prioritize coastal and marine areas, and prepare management plans for enhancing resilience

-   **Coastal and Marine NDC 5**: Restore coastal ecosystems (e.g. coral reefs, mangrove, sand dunes) and improve conservation actions for marine mammals and other threatened species

-   **Fisheries NDC 1**: Ecosystem-based approach to fisheries management (EAFM) adopted in highly climate vulnerable areas to enhance resilience

-   **Forestry NDC 4**: Conservation and enhancement of blue carbon ecosystems including mangroves, sea grass, salt marsh.

-   **L&D NDC 1**: National Level stocktaking and progress reviewing related to all L&D sectors such as but not exclusive to - Agriculture, Livestock and Fisheries, Infrastructure/ Transport, Education, Water, Health, Tele Communication, Tourism, Industries, Gender and Child Protection, Social Protection, Biodiversity and Forestry, Housing, Power and Energy, coastal and marine



​



**LDN targets**:

-   There are no targets identified that relate to this theme.



​




<br>

::: {custom-style='Text'}
The AI model also compared all targets that pertain to Land degradation (LDN), all targets that pertain to Nature (NBSAP), and all targets that pertain to Climate Change (NDC). Of these, 165 pairs show opportunities for further alignment with each other (, as shown in **Table 3.\@ref(tab:tbl14)**. The country might want to explore these targets in more detail and consider areas for further alignment or aligned implementation.).
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl14', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl16
library(flextable)
library(dplyr)
if (nrow(df14)  == 0) {
    invisible(NULL)
} else {df14 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
The National Biodiversity Targets (NBT) and Nationally Determined Contributions (NDC) exhibit several opportunities for alignment in the context of species conservation and ecosystems. Both policies emphasize the importance of participatory spatial planning and the restoration of degraded ecosystems, with specific targets aiming for the conservation of at least 30% of key biodiversity areas by 2030. Additionally, both frameworks address the management of Invasive Alien Species (IAS) and the sustainable use of wild species, highlighting a shared commitment to minimizing biodiversity loss and enhancing ecosystem resilience. However, while the NDC focuses on climate-sensitive areas and resilience-building, the NBT encompasses a broader range of biodiversity considerations, suggesting that further integration could enhance overall effectiveness.
:::

<br>

