#### Value chain management

::: {custom-style='Citation'}
This includes dietary changes, reducing food waste, reducing post-harvest losses, sustainable sourcing and use of resources, supply-chain diversification, improved food processing and retailing, improved energy use in food systems, reducing food loss, and improved supply chain resilience.
:::

<br>

::: {custom-style='Text'}
The AI model identified five targets that could relate to this nature-based solution category:
:::

<br>


**NBSAP targets**:

-   **NBT 10**: Ensure that areas under agriculture, aquaculture, fisheries, mining, tourism, renewable energy generation, and forestry are managed sustainably and cause minimum impact on ecosystems and wild species; promoting food security, all forms of nature-based tourism; conserving and restoring biodiversity, and maintaining ecosystem functions and services to benefit people



​

**NDC targets**:

-   **Agriculture NDC 5 (adaptation)**: Sustainable land use and efficienct resource management for improved production & productivity

-   **Agriculture NDC 6 (adaptation)**: Reduce post-harvest losses and promote value addition of crops in a changing climate

-   **Agriculture NDC 1 (mitigation)**: Reduce post-harvest losses and improve value addition of crops

-   **Agriculture NDC 3 (mitigation)**: Improve adoption of renewable energy for crop farming and processing



​



**LDN targets**:

-   There are no targets identified that relate to this theme.



​




<br>

::: {custom-style='Text'}
The AI model also compared all targets that pertain to Land degradation (LDN), all targets that pertain to Nature (NBSAP), and all targets that pertain to Climate Change (NDC). Of these, four pairs show opportunities for further alignment with each other (as shown in **Table 3.\@ref(tab:tbl10)**. The country might want to explore these targets in more detail and consider areas for further alignment or aligned implementation).
:::

<br>

```{r, echo = FALSE, results='asis', tab.dim = c(6, 6), tab.cap='Targets that show opportunities for further alignment', tab.id='tbl10', tab.cap.pre='Table 3.', tab.lp='sec3'}
#tab.id=tbl12
library(flextable)
library(dplyr)
if (nrow(df10)  == 0) {
    invisible(NULL)
} else {df10 %>% 
    #flextable(cwidth = c(1.5, 1.5, 3)) %>% 
      flextable() %>% 
      width(j = 1, width = 1.5) %>% 
      width(j = 2, width = 1.5) %>% 
      width(j = 3, width = 3) %>% 
      bg(part = 'header', j = 1:3, bg = '#d3e1f1') %>% 
      color(part = 'header', j = 1:3, color = 'black') %>% 
      bold(part = 'header') %>% 
      hline(part = 'all') %>% 
      valign(valign = 'top') %>% 
      align(align = 'justify') %>%  
      #set_table_properties(width = 1, layout = 'autofit') %>% 
      set_table_properties(width = 0.95, layout = 'fixed')
}
```

<br>

::: {custom-style='summ'}
The targets outlined in the Nationally Determined Contributions (NDC) and Nature-Based Tourism (NBT) policies demonstrate notable alignment in the context of value chain management. Both policies emphasize sustainable land use and resource management, with the NDC specifically focusing on improving production and productivity while the NBT highlights the importance of minimizing ecological impacts. Additionally, the NDC's targets on reducing post-harvest losses and enhancing value addition resonate with the NBT's overarching goal of promoting food security and biodiversity conservation. Furthermore, the NDC's commitment to renewable energy adoption in agriculture complements the NBT's sustainable management of various sectors, suggesting a cohesive approach to enhancing supply chain resilience and resource efficiency. Overall, these synergies present opportunities for integrated strategies that could strengthen food systems and environmental sustainability.
:::

<br>

